### ISSUE TITLE
Missing about page

### ISSUE THREAD

**Issue by yakushabb** [ryonakano/konbucase#157]
Konbucase seems to target ElementryOS users. 

I realized there is no about dialog. If it's not against any HIG could you please add it.

**Comment by ryonakano** [comment]
Yes, KonbuCase doesn't have the about dialog currently because it originally targets elementary OS which doesn't prefer it in favor of app details pages in the software center. However, that is not written explicitly in their HIG IIRC and I'm not opposed to adding it.

I guess we just need to prevent the about dialog from being shown on Pantheon and show it on other desktop environments.
